[firestore]
type = "service_account"
project_id = "gen-lang-client-0574792380"  # <-- 請填入你的 Project ID
private_key_id = "d6842c49014ab4158d0218e72df8086af969d202"
client_email = "firebase-adminsdk-fbsvc@gen-lang-client-0574792380.iam.gserviceaccount.com"
client_id = "108645922970207891803"

# ⚠️ 注意：將你的私鑰完整貼入下方三引號之間，包含所有換行符號。
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQClerTeIsQwt+Yi
KnrfKiq2IzVOD9e0+uqSLg01bWO8RsDUlawR0qcm0RwHhelph76SDO7r3DQI3K+F
ben5kyM9eaWQgeUYYpOBRN9aCFQ6/+ApIwN+DIKwspxuGmwEwXavm3ApsINFKULu
f5NdQ2cEAZdXSGN/6FtBrpwV2inzTpY9erEDKGiH/eoYjZUGgyZHlLx9Em2vE0jc
YOo7/fv9f1NtjhQaYUgWmi1sVPFzgNLqGCXw32+RisD94Waf4zTFnG8P8Ws19Ls+
4BibRJOPyQmxfke6yK5vRdiIJY1UKfWM5HWxB8bMZc9ARbctH7V6ikQnAvX5ojvM
W8emgapfAgMBAAECggEABoQl+I2/uJ4zpD3HyxJ/tKtlqNzFcdcXNi/OpyXXF+D+
kxoPuNkl0Hv+Hne4YMaOvqgrhY/zk2b2GT5IrxWLSjTuy//cpx14N7UGfI04AxjA
8xQk/SlkWuC1rNcPUNw50bsNUb7yWsTzFOD8l99H5ufIvCmmejEKqU2SA03gRmuB
Sr44nFJ13gao2MVLHErX8xfwS7BWkZE9bJGuLlTsYRNX4bWNHXJQZWnmxw4VHDkB
1YkqzYQftcWdIbbVQ4cK6uBFtoX8ZZDAq1Xyl1LOhogB6zCS152XT44eRP2SZw8o
e3GGI9gBKyETJq7afEG13LsLRvVl/dfVhljhx9aw5QKBgQDQnHyBuUCYwcJ6xIBO
/LKbkQSrHXmuBwQcuDDE2wI0rF8685LTb/D1gsW9voA5dfWM22jalRDSLHrKeFuN
kekGNRAPOyPhO/7dt334bK3uakhZAMLNjVq+ryxZcpALa/3LdwX/HoyhctbBh67Q
3nAYNteNBjat8MULYT30zSSSHQKBgQDLEfA2W3JSm5ggylTYw2seJbSLQ9uK9kal
DYLQBJIAtoDeDbvDd+UBO4EXTtVEixuNJfJPAsEmrNbvCg4CUyhBPeNDSt5Kn6A7
+e9zRePnzb+8RFwBi0HmZDWvnvgPrW5xvu5s/iz/ICOGaM3bwG/HUf3tKTPUPymT
H0dvM+eFqwKBgQCwTlD74fEyKS+QSlqWZwMcbyee5r5b0horm4+8D8yBb9zcGddR
Ux42oFs2zbXY2lS4wwaPFcStnGH6lFXsBBEI6fe0p6rfRLFV+SpBtrgY80JJ1lbN
GlZDKhE1V5ldzdslBmbPAqagHEpcLawVYqkiDdeGnGXCA+bEg161clsiEQKBgFAN
5lDHhC4kwLhMi15Yy6W63433VllV9UukI+m1o4k8aVkguOC6J0FxH9b8cP7wiBAA
4aFcSKDiimj54cPw3HG74BfrL+7jNtvuEAO1jb8YUXn6yPqi13voDXIKjWhAysV0
q7G0EjERjm+yaVU0a9x76krQb2pA7Dbfod2o7KC5AoGATJSzkUZOYIUj9PxD47Ug
z6fFBHRC5IWMM+tVW/KovpzyFXRRtKfxDEQCbnVlFn/IC/Hqnw/HX1RgNTH/qoJq
xRrggASqvRPvhAgIgJ9d2h2aT5QQ9UgPODmcdMERRzLm6SdLaf4q2IvAqmSi5k5v
DYOOv/g1Y+I7QLO/8Mfs7Bk=
-----END PRIVATE KEY-----
"""

auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "ttps://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40gen-lang-client-0574792380.iam.gserviceaccount.com"
universe_domain = "googleapis.com"